# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Trends in sales'
tagline:          'Datastory'
description:      'Here we present our findigs. You can select a page in the sidebar to go into more detail.'
url:              https://lucianod28.github.io/
baseurl:          "/Ada-project"

author:
  name:           'Data Buffs'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/lucianod28/Ada-project

gems: [jekyll-paginate]
